on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11.9'
                cache: 'pip'
                cache-dependency-path: '**/requirements.txt'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: test server
              run: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
