name: FastAPI Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      fastapi:
        image: tiangolo/uvicorn-gunicorn:python3.11
        ports:
          - 8000:80
        env:
          COMMAND: "uvicorn main:app --host 0.0.0.0 --port 80"
        options: >-
          --health-cmd "curl --fail http://localhost:80/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 在这里，我们不显式启动FastAPI应用，而是让Docker容器启动它
      # 并监听在8000端口上

      - name: Health check
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8000/health; do
            printf '.'
            sleep 5
          done
          echo
          echo "FastAPI application is running and healthy."

      - name: Run tests
        run: |
          pytest