name: FastAPI Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      fastapi:
        image: python:3.11.9-slim
        env:
          COMMAND: "uvicorn app.main:app --host 0.0.0.0 --port 80"
        ports:
          - 8000:80
        options: >-
          --health-cmd "curl -f http://localhost:80/health || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --restart=unless-stopped

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start and Test FastAPI Service
        run: |
          # 等待服务启动
          sleep 10
          # 发送HTTP请求进行健康检查
          if curl -s -o /dev/null -w '%{http_code}' http://localhost:80/health | grep -q 200; then
            echo "FastAPI service is running successfully."
          else
            echo "Failed to start or connect to the FastAPI service."
            exit 1
          fi