on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs :
  build:
    runs-on: ubuntu-latest
    steps:

    - name: server_git_pull
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ./cd_pull.sh
        host: ${{ secrets.HOST_NAME }}
        username: root
        port: 22
        privateKey: ${{ secrets.PRIVATE_KEY}}
