on:
  push:
    branches: [ main ]

jobs :
  build:
    runs-on: ubuntu-latest
    steps:

    - name: show_info
      run: |
        pwd
        ls

    - name: server_git_pull
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ./start_server.sh
        host: ${{ secrets.HOST_NAME }}
        username: root
        port: 22
        privateKey: ${{ secrets.PRIVATE_KEY}}